name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v1
        with:
          arguments: build
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - run: make build
